fix mgf
smith-chem-wisc/mzLib pull request #560
Opened 2020-12-21 03:57 UTC by lonelu

I got a .mgf file from a user. The version 308 could load it, but the current version could not.
It turned out that some mgf files contain empty lines. This pull request skip empty lines in mgf reader.

2020-12-29 16:50 UTC, zrolfs commented
needs unit test

2021-01-18 22:55 UTC, lonelu commented
Unit test added. Please merge this pull request when available.

2021-01-18 23:12 UTC, rmillikin requested changes

2021-01-18 23:12 UTC, rmillikin commented on Mgf/Mgf.cs
> +                if (line == "")
use `string.IsNullOrWhitespace`

2021-01-19 01:12 UTC, lonelu commented on Mgf/Mgf.cs
> +                if (line == "")
Good suggestion!

2021-01-19 19:39 UTC, rmillikin approved these changes

2021-03-12 20:01 UTC, rmillikin approved these changes

2021-03-12 20:02 UTC, merged