[WIP] Flash lfq for percolator
smith-chem-wisc/mzLib pull request #596
Opened 2022-01-19 16:50 UTC by trishorts

I'm updating FlashLFQ for percolator input. There are three issues to deal with:
1. there is no filename, only a file integer. We're hoping the percolator people will update their output as a solution. otherwise the user will have to manually change this.
2. there is no retention time. We're modifying FlashLFQ to read retention time from the raw data file using the scan number supplied in the percolator output.
3. many modified sequences are unreadable because they contain characters with no meaning to our sequence parser. These sequences will be used as unique peptide/proteoform identifiers BUT NOT BE USED TO COMPUTE PEPTIDE/PROTEOFORM MASS.

2022-01-19 18:03 UTC, trishorts commented
ChromatographicPeak has me worried because for percolator the base sequence is null:
![image](https://user-images.githubusercontent.com/16841846/150188062-6f2072d8-595a-4f3a-abe5-bc9b44a01c68.png)

2022-01-19 19:39 UTC, trishorts commented
This PR only handles the necessary changes to the "Identification" object and the use of averagine to return a chemical formula appropriate to the reported monoisotopic mass

2022-01-21 07:43 UTC, percolator commented
Hi Michael,

There are two upcomming updates to percolator that that might help you. We plan to introduce optional columns for
1. filename of the psms.
2. retention time.
Cheers --Lukas

2022-01-21 15:50 UTC, trishorts commented
> Hi Michael,
> 
> There are two upcomming updates to percolator that that might help you. We plan to introduce optional columns for
> 
>     1. filename of the psms.
> 
>     2. retention time.
>        Cheers --Lukas

Thanks Lukas,
Filename was the really big one. I coded a solution to pull RT from index, but I guess I can scrap that (unless we want to keep it around for compatibility to old data). I'll think about it. 

A bigger issue was dealing w/ the protein sequence column, which has mass shifts. I also coded a solution for that that uses the percolator monoisotopic mass to create the proper isotope envelopes using averagine instead of the actual chemical formula of the peptide (which can't be determined from numerical mass shifts). I hope that code can get reviewed and approved soon and incorporated into the release version of flash lfq.

Changes take some time on our end b/c of a stringent review process. Thanks for your help.
-michael

2022-01-21 16:53 UTC, wsnoble commented
I would vote for keeping the RT stuff in FlashLFQ, if possible.  The RT feature in Percolator will only work if the upstream search engine reports that in its output, and I know that some of them do not do so.

Regarding the representation of mass shifts, I don't think we can provide chemical formulas in general, because that's not possible in the case of open search results. Averagine seems like the right solution for this.  Thanks!

2022-01-24 17:54 UTC, rmillikin requested changes

2022-01-24 17:54 UTC, rmillikin commented on FlashLFQ/Identification.cs
> +        public Identification(SpectraFileInfo fileInfo, string ModifiedSequence, double monoisotopicMass,
don't need this second `Identification` constructor; you can use the original constructor and simply pass in `null` for the `BaseSequence` parameter

2022-01-25 18:14 UTC, kyp4 approved these changes
I trust Rob implicitly

2022-01-25 18:17 UTC, merged