Full Averaging Incorporation
smith-chem-wisc/mzLib pull request #679
Opened 2023-01-12 22:05 UTC by nbollis

Eliminating the SpectralAveraging nuget package and creating a project within MzLib

2023-01-16 17:07 UTC, Alexander-Sol requested changes
Test and TestFlashLFQ .csproj files contain an outdated reference to MzLibSpectralAveraging/SpectralAveraging.csproj that cause build failures

2023-01-16 17:58 UTC, Alexander-Sol reviewed
I found AveragedSpectraOutputter to be unintuitive. AveragedSpectraWriter would be more idiomatic.

2023-01-16 18:08 UTC, Alexander-Sol requested changes
Looks great, beautifully encapsulated, extremely readable code. Only a couple of minor issues: "Outputter" instead of "Writer" and creating new MS2 scans instead of modifying in place. (Both issued more clearly defined in individual comments.)

2023-01-16 21:18 UTC, Alexander-Sol approved these changes

2023-01-16 21:56 UTC, nbollis commented on mzLib/SpectralAveraging/Algorithms/SpectraFileAveraging.cs
> +                MsDataScan newScan = new(scan.MassSpectrum, scanNumberIndex, scan.MsnOrder, scan.IsCentroid,
This has been fixed in the recent commits

2023-01-16 21:57 UTC, nbollis commented
> Looks great, beautifully encapsulated, extremely readable code. Only a couple of minor issues: "Outputter" instead of "Writer" and creating new MS2 scans instead of modifying in place. (Both issued more clearly defined in individual comments.)

Both of these have been addressed and changed

2023-01-18 00:30 UTC, acesnik approved these changes
I haven't done a deep review, but this looks well tested and well integrated.

2023-01-18 18:01 UTC, Alexander-Sol approved these changes

2023-01-19 20:54 UTC, merged