Development dependency issue
smith-chem-wisc/mzLib pull request #699
Opened 2023-04-17 18:32 UTC by nbollis

Development was a dependency of test, but was not getting packaged. This PR should resolve that issue by removing development as a dependency of test

2023-04-17 21:59 UTC, Alexander-Sol requested changes
You should edit the nuspec file to include Readers and remove/change ThermoReader. 

There's something else going on too. Even with Readers included in the nuspec, MetaMorpheus doesn't load Readers.dll. Could be due to an issue with Reader.csproj, which has a couple of main differences compared to other .csproj files.

2023-04-21 01:16 UTC, acesnik submitted a review, later dismissed

2023-04-21 01:16 UTC, acesnik commented on mzLib/mzLib.nuspec
> -    <version>5.0.538</version>
Shouldn't this be `1.0.539`?

2023-04-21 01:16 UTC, acesnik commented on mzLib/Test/FileReadingTests/TestRawFileReader.cs
> -        [Test]
Nice work on structuring this below

2023-04-25 19:37 UTC, Alexander-Sol approved these changes

2023-04-25 23:20 UTC, avcarr2 approved these changes

2023-04-25 23:20 UTC, avcarr2 commented on mzLib/MassSpectrometry/MsDataFile.cs
>      // TODO: Define scope of class
TODO is still here.

2023-04-26 15:50 UTC, trishorts approved these changes

2023-04-26 15:50 UTC, merged