Fixed bug where pwsm.ChemicalFormula threw null reference exception
smith-chem-wisc/mzLib pull request #707
Opened 2023-05-25 19:01 UTC by Alexander-Sol

Fixes issue #706

2023-05-30 21:42 UTC, elaboy approved these changes

2023-05-30 22:27 UTC, nbollis approved these changes

2023-05-31 15:59 UTC, avcarr2 requested changes

2023-05-31 16:04 UTC, Alexander-Sol commented on mzLib/Proteomics/ProteolyticDigestion/PeptideWithSetModifications.cs
> +                        break;
It should be a break. If you have one mod without a chemical formula, it's impossible to report the full chemical formula of the peptide.

Returning a chemical formula that doesn't match the peptide's mass would be worse than returning null

2023-05-31 16:05 UTC, Alexander-Sol commented on mzLib/Test/TestPeptideWithSetMods.cs
> +                    { "Carbamidomethyl on C", new Modification(_originalId: "Carbamidomethyl", _modificationType: "Common Fixed",
Issue is addressed on lines 1069, 1071, and 1074

2023-05-31 16:07 UTC, avcarr2 approved these changes

2023-05-31 16:08 UTC, merged