fix gz decompress so that we get the complete xml database
smith-chem-wisc/mzLib pull request #715
Opened 2023-06-29 19:59 UTC by trishorts

There has been intermittent trouble decompressing an xml file that is compressed as .gz. I think the trouble is that we were simultaneously streaming the decompression and the xml to yield protein entries. In this PR, i separate this into two steps. First I completely decompress the file into a temp.xml. Then i stream this temp file into protein entries. Then I delete the temp file.

2023-06-29 20:29 UTC, Alexander-Sol requested changes
I saw this issue with a .gz compressed fasta file. Can we add in a test for this situtaion

2023-07-03 16:31 UTC, nbollis approved these changes

2023-07-03 17:46 UTC, elaboy approved these changes

2023-07-03 18:28 UTC, nbollis approved these changes

2023-07-03 18:32 UTC, merged