Create CONTRIBUTING.md
smith-chem-wisc/mzLib pull request #742
Opened 2023-11-27 19:31 UTC by trishorts

2023-12-07 16:51 UTC, nbollis submitted a review, later dismissed

2023-12-11 21:15 UTC, acesnik requested changes

2023-12-11 21:15 UTC, acesnik commented on CONTRIBUTING.md
> +# Contributing to Transcriptase
Change to mzLib?

2023-12-11 21:15 UTC, acesnik commented on CONTRIBUTING.md
> +## Report bugs using Github's [issues](https://github.com/briandk/transcriptase-atom/issues)
Correct link here

2023-12-11 21:15 UTC, acesnik commented on CONTRIBUTING.md
> +We use GitHub issues to track public bugs. Report a bug by [opening a new issue](); it's that easy!
Missing link

2023-12-11 21:15 UTC, acesnik commented on CONTRIBUTING.md
> +  - Give sample code if you can. [My stackoverflow question](http://stackoverflow.com/q/12488905/180626) includes sample code that *anyone* with a base R setup can run to reproduce what I was seeing
Change to C#?

2023-12-12 17:31 UTC, nbollis approved these changes

2023-12-12 17:33 UTC, Alexander-Sol approved these changes

2023-12-12 17:44 UTC, acesnik approved these changes

2023-12-12 17:53 UTC, merged