Johnny Deconv 1st Step
smith-chem-wisc/mzLib pull request #791
Opened 2024-08-02 19:24 UTC by nbollis

Added the boilerplate for John to go in and add his dlll

2024-08-05 16:12 UTC, trishorts commented
maybe we can add something for each new decon method about which of the two camps it falls into.

https://github.com/smith-chem-wisc/mzLib/discussions/694

2024-08-06 14:14 UTC, trishorts commented on mzLib/MassSpectrometry/Deconvolution/Algorithms/IsoDecAlgorithm.cs
> +            public float mz;
would be good to use our standard variable names for these features.

2024-08-06 14:14 UTC, trishorts commented on mzLib/MassSpectrometry/Deconvolution/Algorithms/IsoDecAlgorithm.cs
> +                List<double> listofratios = new List<double>();
better variable name

2024-08-06 19:48 UTC, trishorts commented
What mass range and resolution will this method apply to?

2024-10-04 19:22 UTC, nbollis commented on mzLib/Development/DeconvolutionDevelopment/StandardDeconvolutionTest.cs
>      [ExcludeFromCodeCoverage]
You will need to uncoment this line in order to pass checks.

2024-10-08 15:57 UTC, trishorts commented
Patch coverage will need to be >= 90%

2025-01-08 23:27 UTC, jgpavek approved these changes

2025-01-09 20:10 UTC, Alexander-Sol requested changes
I'm not sure how the neutral mass spectra fit together with IsoDec. Does isodec return neutral mass spectra?

Other than that, a couple minor changes, but overall looks good

2025-01-09 20:40 UTC, nbollis commented on mzLib/MassSpectrometry/MzSpectra/IsotopicEnvelope.cs
> +            MostAbundantObservedIsotopicMass = peaks.MaxBy(p => p.intensity).mz * Math.Abs(chargestate);
Unfortunately, this is not a bug. The MostAbundantObservedIsotopicMass was originally implemented to be without the effect of protons and ESI. I am not sure who wrote it or made it this way, but I have taken steps to ensure it is not visible outside of the context of MassSpectrometry. It appears to only be used to test deconvolution.

2025-01-09 20:41 UTC, nbollis commented
> I'm not sure how the neutral mass spectra fit together with IsoDec. Does isodec return neutral mass spectra?

Neutral mass spectrum does not fit with IsoDec. Isodec returns isotopic envelopes. The reason you see changes in Deconvoluter about neutral mass spectra, was me moving it from processing in the main method to a helper method. This helps to ensure a smooth IEnumerable return by the consuming method.

2025-01-09 21:44 UTC, Alexander-Sol approved these changes

2025-01-10 18:52 UTC, jgpavek approved these changes

2025-01-10 22:15 UTC, merged