[WIP] Added interfaces for Quant and MsFragger result files
smith-chem-wisc/mzLib pull request #792
Opened 2024-08-19 18:36 UTC by mzhastings

2024-09-12 23:29 UTC, nbollis requested changes
Great idea. Working with all the fragger individual files is very annoying, this will  be a lovely addition to our ever-growing collection of readers

2024-09-12 23:29 UTC, nbollis commented on mzLib/Readers/ExternalResults/ResultFiles/ExperimentAnnotationFile.cs
How is this different than our current experimental design file? Is it a fragger output?

2024-09-12 23:29 UTC, nbollis commented on mzLib/Readers/ExternalResults/IndividualResultRecords/ExperimentAnnotation.cs
> +            BadDataFound = null,
BadDataFound = null will skip all lines it cannot understand, instead of crashing. Is this the intended behavior?

2024-09-12 23:29 UTC, nbollis commented on mzLib/Readers/Util/SupportedFileTypes.cs
>          }
Need to add a line to ParseFileType for the annotation file

2024-09-12 23:29 UTC, nbollis commented on mzLib/Test/TestMsFraggerCombinedResults.cs
> +        {
This test should have a check at the beginning to delete the file if it already exists. It should also delete the file at the end

2024-09-12 23:29 UTC, nbollis commented on mzLib/Test/FileReadingTests/TestSupportedFileExtensions.cs
You should add a test case to this method for your new file type

2024-09-13 16:21 UTC, mzhastings commented on mzLib/Readers/ExternalResults/ResultFiles/ExperimentAnnotationFile.cs
It is a fragger output within the results folder containing a summary of the samples including their names and the full file path to their raw files. This is necessary for finding the directories within the results folder with the psm.tsv files since the names of the directories are the sample names. The raw file paths are used to build the dictionary linking file names to their file paths.

2024-09-19 17:29 UTC, nbollis approved these changes

2024-09-24 19:04 UTC, Alexander-Sol approved these changes

2024-10-30 15:02 UTC, merged