DecoyScrambler now accounts for modifications
smith-chem-wisc/mzLib pull request #795
Opened 2024-08-21 20:51 UTC by Alexander-Sol

Now, when creating scrambled decoy proteins, modifications come along for the ride. 

Rearranges the OneBasedPossibleLocalizedModifications dictionary to correspond to the new scrambled protein sequenc

2024-08-21 22:20 UTC, nbollis requested changes
What happens with terminal modifications? We have Modifications that are designated as Protein N/C terminal as well as Peptide N/C terminal. How are these cases handled?

2024-08-21 22:20 UTC, nbollis commented on mzLib/Proteomics/Protein/Protein.cs
> +
Instead of cloning, then checking if anything is contained later, could you scramble, check if there are mods, then clone?

2024-08-21 22:20 UTC, nbollis commented on mzLib/Test/TestProteinDigestion.cs
> +
simple cleanup can be done here

2024-08-23 16:04 UTC, trishorts approved these changes

2024-08-23 17:49 UTC, nbollis approved these changes

2024-08-23 18:10 UTC, merged