Tims tof reader
smith-chem-wisc/mzLib pull request #812
Opened 2024-12-05 00:44 UTC by Alexander-Sol

Added support for timsTOF data files (.d)

TimsTofFileReader is a child class of MsDataFile. Currently, only DDA PASEF data is supported.

Dynamic loading is not supported at this time.

Replace PR #800

2025-01-16 21:24 UTC, trishorts commented on mzLib/Readers/Readers.csproj
> +		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
"In a C# project file (.csproj), the "AllowUnsafeBlocks" property within a "PropertyGroup" is used to enable the compilation of code containing "unsafe" blocks, which allows the use of pointers and direct memory manipulation, but should be used with caution due to the potential for memory management issues and security risks."

2025-01-16 22:23 UTC, nbollis requested changes
Looks great overall. Only minor points were raised in my comments.

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/Records.cs
Consider making these readonly ref structs if they are intended to be shortlived intermediates of data. That would ensure they are only allocated to the stack.

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsConversion.cs
A lot of untested options here. Is this a point of concern?

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TofSpectraMerger.cs
There is a lot going on here. Some summary comments would be lovely.

2025-01-16 22:23 UTC, nbollis commented on mzLib/mzLib.nuspec
>          <dependency id="Microsoft.Extensions.ObjectPool" version="9.0.0" />
I trust you that we need to pack CsvHelper. I am curious as to why we need it now but did not previously

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsTofFileReader.cs
> +        // ion mobility valuess. When reading the file, multiple scans from the same frame are collapsed into
What are they collapsed into? I am on the edge of my seat

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsTofFileReader.cs
> +        {
Should you check to make sure the connection is not open already?

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsTofFileReader.cs
This class should probably implement IDisposable to ensure connections are closed upon losing scope.

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsTofFileReader.cs
> +        public TimsDataScan? GetScanFromPrecursorAndFrameIdFromDynamicConnection(int precursorId, int frameId, IFilteringParams filteringParams = null)
You throw on null recordForPrecursor, does this need to be nullable in that case?

2025-01-16 22:23 UTC, nbollis commented on mzLib/Readers/timsTOF/TimsTofFileReader.cs
> +            if (FrameProxyFactory == null)
Will this ever get hit?

2025-01-17 01:18 UTC, nbollis approved these changes

2025-01-17 16:30 UTC, trishorts approved these changes

2025-01-19 20:36 UTC, RayMSMS approved these changes

2025-01-19 22:02 UTC, merged